# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'movesense-swiftapp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for movesense-swiftapp
  pod 'Movesense', :git => 'ssh://git@altssh.bitbucket.org:443/suunto/movesense-mobile-lib.git', :branch => 'master'
  pod 'PromiseKit', '~> 4.1'
  pod 'Toast-Swift', '~> 2.0.0'
  pod 'SwiftyJSON'

  pod 'React', :path => '../node_modules/react-native', :subspecs => [
    'Core',
    'DevSupport', # Include this to enable In-App Devmenu if RN >= 0.43
    'RCTText',
    'RCTNetwork',
    'BatchedBridge',
    'RCTWebSocket',
    'RCTImage' # needed for debugging
    # Add any other subspecs you want to use in your project
  ]
  # Explicitly include Yoga if you are using RN >= 0.42.0
  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
end
